mount-nv: fail on formating error
If the formating fails when passing "--format", we currently only
report an error message and continue with other possible errors then
exit 0. First it's important to emit a relevant error message, and
second we must exit immediately upon such a failure.

diff --git a/scripts/mount-nv b/scripts/mount-nv
--- a/scripts/mount-nv
+++ b/scripts/mount-nv
@@ -86,7 +86,9 @@ if mkdir -p $PERSIST_DIR 2>/dev/null; then
 		tr '\000' '\377' </dev/zero | dd of=$mtdblock bs=64k 2>/dev/null
 		mount -t jffs2 $mtdblock $PERSIST_DIR 2>/dev/null
 		if [ "$?" != "0" ] ; then
-			echo "Unable to format."
+			echo "Error: unable to format $FLASH_NV using JFFS2."
+			modprobe -r block2mtd mtdblock 2>/dev/null
+			exit 1
 		fi
 	else
 		echo "Error: mount failed, nv seems not formatted use option --format."
